num_users = 20
places_by_tag = {
    'Food': ['TRUFFLES', 'TACO BELL', 'MCDONALDS', 'BURGER KING', 'HALDIRAMS', 'PARADISE BIRYANI', 'SARAVANA BHAVAN', 'KARIMS', 'BARBEQUE NATION', 'DOMINOS PIZZA', 'MANOJ SWEETS', 'KANTI SWEETS', 'ESHA SWEETS', 'NAGARJUNA BIRYANI', 'MANIS DUM BIRYANI', 'MEGHNA FOODS'],
    'Medical': ['APOLLO PHARMACY', '1MG', 'MEDPLUS', 'NETMEDS', 'FORTIS', 'MAX HEALTHCARE', 'MEDANTA', 'AIIMS', 'COLUMBIA ASIA', 'NARAYANA HEALTH', 'ARUN MEDICAL', 'RAVI MEDICINE'],
    'Shopping': ['DECATHLON', 'IKEA', 'AMAZON', 'FLIPKART', 'BIG BAZAAR', 'RELIANCE DIGITAL', 'TANISHQ', 'FABINDIA', 'PANTALOONS', 'SHOPPERS STOP'],
    'Subscription': ['SPOTIFY', 'NETFLIX', 'PRIME VIDEO', 'HOTSTAR', 'ZEE5', 'SONY LIV', 'DISNEY+ HOTSTAR', 'ALT BALAJI', 'GAANA', 'VODAFONE RED', 'BUMBLE', 'TINDER'],
    'Travel': ['MAKEMYTRIP', 'IRCTC', 'YATRA', 'GOIBIBO', 'AIR INDIA', 'INDIGO', 'SPICEJET', 'OYO ROOMS', 'TRIVAGO', 'BOOKING.COM']
}
num_transactions_per_user = 50
